#config.yaml
flows:
  - "**"
includeTags:
  - AT2
  - AT3
excludeTags:
  - login
  - AT5
  - AT7
  - AT9
  - AT10
  - AT11
  - AT12
  - AT13
  - AT14
  - AT15
  - AT16
  - AT17
  - AT18
  - AT19
  - AT20
  - AT21
  - AT22
  - AT23-25
  - AT26-27
  - AT28-30
  - AT31
  - AT32-34
  - AT35-37
  - AT38-40
  - AT41-43
  - AT44-46
  - AT47-49
  - AT50-52
  - AT53-54
  - AT55

executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT2
        - AT3
